@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": false,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.scytalys.technikon.service.impl.PropertyOwnerServiceImpl",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_197470096 { 
   	label=scytalys
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_882458853 { 
   	label=technikon
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   PropertyOwnerRepository2049651632[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)PropertyOwnerRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ findByEmail(email: String): Optional&lt;PropertyOwner&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findByUsername(username: String): Optional&lt;PropertyOwner&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

PropertyOwnerService635116689[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)PropertyOwnerService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createUpdateUserDto(id: long, password: String, email: String, address: String, errorMessage: String): UserUpdateDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ createUser(user: PropertyOwner): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ softDeleteUser(propertyOwner: PropertyOwner)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserAddress(address: String, propertyOwner: PropertyOwner)</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyConstraintsEmail(email: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyConstraintsId(id: Long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyConstraintsUsername(username: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

PropertyOwnerServiceImpl124484289[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PropertyOwnerServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   propertyOwnerRepository: PropertyOwnerRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createUpdateUserDto(id: long, password: String, email: String, address: String, errorMessage: String): UserUpdateDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ createUser(user: PropertyOwner): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ createUserCreationDto(user: User, errorMessage: String): UserResponseDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ createUserSearchDto(id: long, username: String, email: String, errorMessage: String): UserResponseToSearchDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteUser(propertyOwnerId: long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchUser(id: long): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchUser(username: String): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ softDeleteUser(propertyOwner: PropertyOwner)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserAddress(address: String, propertyOwner: PropertyOwner)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserEmail(email: String, user: User)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserPassword(password: String, user: User)</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyConstraintsEmail(email: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyConstraintsId(id: Long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyConstraintsUsername(username: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SampleData2033362088[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SampleData</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   propertyOwnerService: PropertyOwnerService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propertyRepairService: PropertyRepairService [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ myCommandLineRunner(): CommandLineRunner</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserService635116689[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)UserService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createUserCreationDto(user: User, errorMessage: String): UserResponseDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ createUserSearchDto(id: long, username: String, email: String, errorMessage: String): UserResponseToSearchDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteUser(UserId: long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchUser(Id: long): User</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchUser(username: String): User</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserEmail(email: String, user: User)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserPassword(password: String, user: User)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];
} 
} 

'edges    
PropertyOwnerService635116689 -> PropertyOwnerServiceImpl124484289[arrowhead=none, arrowtail=empty, dir=both];
PropertyOwnerServiceImpl124484289 -> PropertyOwnerRepository2049651632[label="propertyOwnerRepository
[0..1]"];
SampleData2033362088 -> PropertyOwnerService635116689[label="propertyOwnerService
[0..1]"];
UserService635116689 -> PropertyOwnerService635116689[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml