@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.scytalys.technikon.service.impl.AdminServiceImpl",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_197470096 { 
   	label=scytalys
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_882458853 { 
   	label=technikon
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   AdminController931943586[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AdminController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   adminService: AdminService [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># findAdmins(): List&lt;Admin&gt;</TD></TR>
<TR><TD ALIGN="LEFT" ># findOwners(fromYear: String, fromMonth: String, fromDay: String, toYear: String, toMonth: String, toDay: String): List&lt;PropertyOwner&gt;</TD></TR>
<TR><TD ALIGN="LEFT" ># findProperties(ownerTin: String): List&lt;Property&gt;</TD></TR>
<TR><TD ALIGN="LEFT" ># findRepairs(propertyTin: String): List&lt;PropertyRepair&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AdminServiceImpl124484289[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AdminServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   adminRepository: AdminRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propertyOwnerRepository: PropertyOwnerRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propertyRepairRepository: PropertyRepairRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propertyRepository: PropertyRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ create(admin: Admin): Admin</TD></TR>
<TR><TD ALIGN="LEFT" >+ createOwner(propertyOwner: PropertyOwner): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ delete(id: Long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ findAll(): List&lt;Admin&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findById(id: Long): Admin</TD></TR>
<TR><TD ALIGN="LEFT" >+ findOwner(tin: String): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ findProperty(tin: String): Property</TD></TR>
<TR><TD ALIGN="LEFT" >+ getDueRepairs(property: Property): List&lt;PropertyRepair&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getRegisteredOwners(from: LocalDate, to: LocalDate): List&lt;PropertyOwner&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getRegisteredProperties(owner: PropertyOwner): List&lt;Property&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(id: Long, admin: Admin): Admin</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SampleData2033362088[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SampleData</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   adminService: AdminService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   jwtService: JwtService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propertyMapper: PropertyMapper [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propertyOwnerService: PropertyOwnerService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propertyRepairMapper: PropertyRepairMapper [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propertyRepairService: PropertyRepairService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propertyService: PropertyService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userInfoService: UserInfoService [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ myCommandLineRunner(): CommandLineRunner</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
AdminController931943586 -> AdminServiceImpl124484289[label="adminService
[0..1]", arrowhead=none];
SampleData2033362088 -> AdminServiceImpl124484289[label="adminService
[0..1]", arrowhead=none];
    
}
@enduml