@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.scytalys.technikon.service.impl.PropertyOwnerServiceImplTest",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_197470096 { 
   	label=scytalys
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_882458853 { 
   	label=technikon
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Admin25216822[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Admin</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># canEqual(other: Object): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PropertyOwner25216822[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PropertyOwner</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   address: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   phoneNumber: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># canEqual(other: Object): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PropertyOwnerServiceImpl124484289[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PropertyOwnerServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   propertyOwnerRepository: PropertyOwnerRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createUser(user: PropertyOwner): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ createUserCreationResponseDto(user: User, errorMessage: String): UserResponseDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ createUserSearchResponseDto(id: long, username: String, email: String, errorMessage: String): UserResponseToSearchDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ createUserUpdateResponseDto(id: long, password: String, email: String, address: String, errorMessage: String): UserUpdateDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteUser(propertyOwnerId: long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchUserByEmail(email: String): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchUserById(id: long): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchUserByUsername(username: String): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ softDeleteUser(propertyOwner: PropertyOwner)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserAddress(address: String, propertyOwner: PropertyOwner)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserEmail(email: String, user: User)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserPassword(password: String, user: User)</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyConstraintsEmail(email: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyConstraintsId(id: Long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyConstraintsUsername(username: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PropertyOwnerServiceImplTest124484289[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PropertyOwnerServiceImplTest</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   propertyOwner: PropertyOwner [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propertyOwnerRepository: PropertyOwnerRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propertyOwnerService: PropertyOwnerServiceImpl [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ testCreateUser()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testCreateUserCreationResponseDto()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testCreateUserSearchResponseDto()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testCreateUserUpdateResponseDto()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testDeleteUser()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testSearchUserByEmail()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testSearchUserByEmailFail()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testSearchUserById()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testSearchUserByIdFail()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testSearchUserByUsername()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testSearchUserByUsernameFail()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testSoftDeleteUser()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testUpdateUserAddress()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testUpdateUserEmail()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testUpdateUserPassword()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testVerifyConstraintsEmailFailure()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testVerifyConstraintsIdFailure()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testVerifyConstraintsUsernameFailure()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

User25216822[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)User</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   email: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: long [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   isActive: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   password: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   surname: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   username: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   version: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># canEqual(other: Object): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserResponseDto686682215[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserResponseDto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   errorMessage: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   user: User [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ errorMessage(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ user(): User</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserResponseToSearchDto686682215[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserResponseToSearchDto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   email: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   errorMessage: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: long [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   username: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ email(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ errorMessage(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ id(): long</TD></TR>
<TR><TD ALIGN="LEFT" >+ username(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserUpdateDto686682215[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserUpdateDto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   address: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   email: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   errorMessage: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: long [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   password: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ address(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ email(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ errorMessage(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ id(): long</TD></TR>
<TR><TD ALIGN="LEFT" >+ password(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
PropertyOwnerServiceImplTest124484289 -> PropertyOwner25216822[label="propertyOwner
[0..1]"];
PropertyOwnerServiceImplTest124484289 -> PropertyOwnerServiceImpl124484289[label="propertyOwnerService
[0..1]"];
User25216822 -> Admin25216822[arrowhead=none, arrowtail=empty, dir=both];
User25216822 -> PropertyOwner25216822[arrowhead=none, arrowtail=empty, dir=both];
UserResponseDto686682215 -> User25216822[label="user
[0..1]"];
    
}
@enduml