@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.scytalys.technikon.service.impl.PropertyOwnerServiceImpl",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_197470096 { 
   	label=scytalys
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_882458853 { 
   	label=technikon
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   PropertyOwnerController931943586[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PropertyOwnerController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   propertyOwnerService: PropertyOwnerService [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createPropertyOwner(newUser: PropertyOwner): ResponseEntity&lt;UserResponseDto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteUser(id: long, version: long): ResponseEntity&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findUserByEmail(email: String): ResponseEntity&lt;UserResponseDto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findUserById(id: Long): ResponseEntity&lt;UserResponseDto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findUserByUsername(username: String): ResponseEntity&lt;UserResponseDto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ handleDataException(e: Exception): ResponseEntity&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserAddress(address: String, id: long, version: long): ResponseEntity&lt;UserResponseDto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserEmail(email: String, id: long, version: long): ResponseEntity&lt;UserResponseDto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserPassword(password: String, id: long, version: long): ResponseEntity&lt;UserResponseDto&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PropertyOwnerServiceImpl124484289[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PropertyOwnerServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   propertyOwnerRepository: PropertyOwnerRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createUser(user: PropertyOwner): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ createUserResponseDto(id: long, username: String, email: String, version: long): UserResponseDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteUser(propertyOwnerId: long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchUserByEmail(email: String): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchUserById(id: long): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchUserByUsername(username: String): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ softDeleteUser(id: long, version: long): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserAddress(id: long, address: String, version: long): PropertyOwner</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserEmail(id: long, email: String, version: long): User</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUserPassword(id: long, password: String, version: long): User</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyConstraintsEmail(email: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyConstraintsId(id: Long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyConstraintsUsername(username: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifySearchResult(propertyOwner: User)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SampleData2033362088[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SampleData</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   propertyOwnerService: PropertyOwnerService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propertyRepairService: PropertyRepairService [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ myCommandLineRunner(): CommandLineRunner</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
PropertyOwnerController931943586 -> PropertyOwnerServiceImpl124484289[label="propertyOwnerService
[1]", arrowhead=none];
SampleData2033362088 -> PropertyOwnerServiceImpl124484289[label="propertyOwnerService
[0..1]", arrowhead=none];
    
}
@enduml